### ISSUE TITLE
Is there an option to display single line wave?

### ISSUE THREAD

**Issue by chea1tei** [woofers/react-wavify#110]
Is there an option to display single line wave?

**Comment by woofers** [comment]
@chea1tei Not sure there is enough detail here that describes the issue here.

But if your asking if there is a way to apply only a stroke/border to the wave, it should be possible by applying a drop-shadow via a CSS filter: 

Just adjust the width and color here:

```css
svg {
  filter: drop-shadow(0px -8px 0px #fff);
}
```

<img src="https://github.com/woofers/react-wavify/assets/7284672/e6909543-111b-4217-96cf-0fbfb65ab94f" width="400">

Please let me know if this solves the issue and if not please provide more detail.

**Comment by chea1tei** [comment]
Hello @woofers 

I would like to do a svg line animation wave like this from the screenshot.. i tried using the filter css but no luck with it.. any change this is possible?
![Screenshot 2023-08-21 at 9 45 16 AM](https://github.com/woofers/react-wavify/assets/15363982/858c470a-6aeb-460c-b83e-015eb07a4ffb)

**Comment by woofers** [comment]
@chea1tei Take a look at this Codesandbox:

https://codesandbox.io/s/wave-blend-mode-292x5k?file=/src/index.js

If you absolute position 2 waves on top of each other, you can set the fill to white and use `mix-blend-mode: darken`.  This will make the solid part of the wave transparent and then you can apply `filter: drop-shadow(0px -8px 0px #123)` to set the outline color.

**Comment by chea1tei** [comment]
@woofers thank you! really close to it! i tried changing the border color to #16ADA3 but it seems very darken ( not original color ) any alternate for this ?

**Comment by woofers** [comment]
@chea1tei You will need to adjust the color to compensate for the blend mode.  You can try with `fill="rgba(0, 0, 0, 0)"` , but from what I can see the fill color will adjust the line opacity as-well.  `mix-blend-mode` gets around this but comes at the cost of having to offset the color.  I don't see any way around this.
