### ISSUE TITLE
I can't change options dynamically 

### ISSUE THREAD

**Issue by WaelFa** [woofers/react-wavify#64]
It seems that when I set the height as variable and change it in the state of the component, the height of the wave doesn't change and stays the same as the initial value.

**Comment by woofers** [comment]
Hi @WaelFa, thanks for reporting this issue.

Since I'm not making use of `defaultProps` (as it won't work for a JSON object), the component only updated the `options` field in the constructor.  

I made some changes in `v1.2.2` (#65) that will listen for props change and update the fields accordingly. 

Just be aware that changing any of the `options` props will not smoothly animate the change,
but will instead jump straight to the new state.  However if you want some sort of animation when you change the state, I would recommended maybe having 2 wave components where the opacity is transitioned using CSS to simulate a smooth transition.

Please let me know if the changes in `v1.2.2` work for you and then I can close out the issue.

**Comment by WaelFa** [comment]
Thanks for the fix, It works perfectly.
I'll see what I can do about the transition

**Comment by woofers** [comment]
@WaelFa Awesome, I'll close this issue out.  Feel free to open a feature request for the transition as I can provide an example if needed.

**Comment by WaelFa** [comment]
yes, it would be very helpful in fact if you provided an example @woofers

**Comment by woofers** [comment]
@WaelFa Alright I had a quick try at animating the height of a wave.

The first example uses 2 waves and simply animates out the opacity to fade-in and out smoothly:
https://codesandbox.io/s/wave-opacity-k7hfu
I don't think it turned out that well but if you only need to switch between two different configurations it might be okay.

The second example keeps the actual wave height the same, but animates the position of the wave
on top of another `div` with the same colour.  This gives the effect that the wave's height is changing:
https://codesandbox.io/s/wave-height-u0ecn 
I think this is probably closer to what your looking for.

Hopes these help.

**Comment by WaelFa** [comment]
Thank you very much, that's exactly what I've been looking for
