### ISSUE TITLE
Multiple waves demo

### ISSUE THREAD

**Issue by yann510** [woofers/react-wavify#93]
Hey, this is a really cool project, love it!

I think it would be nice to add a demo where you have multiple waves stacked to create an "ocean" effect like in this code pen: https://codepen.io/tedmcdo/pen/PqxKXg
I'm pretty sure this would be possible using your library.

**Comment by woofers** [comment]
Hi @yann510,

For the time being, I likely won't be adding any more demos to the demo site.
However if your interested, PRs are welcome to this repo.

With all that being said, you should be able to use absolute positioning 
with 2 wave components in a container, to create a staggered wave effect.

Take a look at this CodeSandbox:

https://codesandbox.io/s/wave-opacity-forked-od829

Its not the exact effect however you can stagger the waves in this way.

**Comment by yann510** [comment]
Hey, I tried to add the double wave to your project in the README, but when I run `yarn start` in the demo folder, I'm getting the following error:
![image](https://user-images.githubusercontent.com/6068943/143687732-9dcef482-5b46-40f2-9e95-9a04b7209c6c.png)

Yes, I did install the packages in both the root and demo folder.

**Comment by woofers** [comment]
Hi @yann510, 

The demo folder uses the local build of the react-wavify library from the root folder.

Since the actual react-wavify library is not built yet, it complains about not being able to find it.

This can be fixed by running `yarn build` in the root folder, and `yarn add ../.` in the demo folder.

------

Alternatively you can install the version from NPM to develop locally by running `yarn add react-wavify` in the demo.

Thanks for pointing this out as this repo should be more contributor friendly and I hope to have the time to update this soon to include better instructions in the Readme.

**Comment by yann510** [comment]
Thanks for the reply, unfortunately, I'm busy with work these days, and I won't be able to carve time to implement this demo. So I will close the issue.
